#!/bin/bash

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

XAUTHFILE=

onexit()
{
        if [ ! "$XAUTHFILE" = "" ]; then
                rm -f $XAUTHFILE
        fi
}

if [ -z ${VGL_DISPLAY+x} ]; then
        export VGL_DISPLAY=/dev/dri/card0
fi
XAUTHFILE=`mktemp ~/.Xauthority.XXXXXX`
case $VGL_DISPLAY in
*:*)
        if [ -f /etc/opt/VirtualGL/vgl_xauth_key ]; then
                xauth merge /etc/opt/VirtualGL/vgl_xauth_key
        fi
        xauth nlist $DISPLAY $VGL_DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTHFILE nmerge -
        ;;
*)
        xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTHFILE nmerge -
        ;;
esac
chmod 444 $XAUTHFILE

. `dirname $0`/dockername
# Execute /bound/$USER/.smc-docker/run, if it exists and is executable.  This
# allows for per-user customization of the Docker container.  The per-user run
# script can override DOCKERUSER or DOCKERIMAGE, which will cause this script
# to run a different Docker image than the default image that was set by the
# dockername script.  The per-user run script can also run the Docker image
# itself and set DOCKERSTARTED=1 to instruct this script not to run the Docker
# image.
if [ -x /bound/$USER/.smc-docker/run ]; then
  echo "Executing /bound/$USER/.smc-docker/run ..."
  . /bound/$USER/.smc-docker/run
  if [ $DOCKERSTARTED = 1 ]; then
    exit 0
  fi
fi
docker run \
        --device=/dev/dri \
        -e DISPLAY \
        -e VGL_DISPLAY \
        --gpus all \
        --ipc host \
        --rm \
        -v $XAUTHFILE:/home/docker/.Xauthority \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /data/docker_bind/$USER:/home/docker/mydata \
        -v /data/docker_bind/$USER/Downloads:/home/docker/Downloads \
        --memory=16g \
        --memory-reservation=10g \
        --cpus=4 \
        --name $USER-${DISPLAY//:} \
        $DOCKERUSER/$DOCKERIMAGE \
        xfce4-session
